apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authenication-mongo-depl
spec:
  replicas: 1
  serviceName: authenication-mongo
  selector:
    matchLabels:
      app: authenication-mongo
  template:
    metadata:
      labels:
        app: authenication-mongo
    spec:
      containers:
        - name: authenication-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: authenication-mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: authenication-mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: authenication-mongo-srv
spec:
  selector:
    app: authenication-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017