apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels: 
        app: authentication
    spec:
      containers:
        - name: authentication
          image: us.gcr.io/amp-dev-376317/authentication
          env:
            - name: MONGO_URI
              value: mongodb://authenication-mongo-srv:27017/auth
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwr 
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-srv
spec:
  selector:
    app: authentication
  ports:
    - name: authentication
      protocol: TCP
      port: 3000
      targetPort: 3000