apiVersion: apps/v1
kind: Deployment
metadata:
  name: properties-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: properties
  template:
    metadata:
      labels: 
        app: properties
    spec:
      containers:
        - name: properties
          image: us.gcr.io/amp-dev-376317/properties
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'amp'
            - name: MONGO_URI
              value: mongodb://properties-mongo-srv:27017/properties
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwr 
---
apiVersion: v1
kind: Service
metadata:
  name: properties-srv
spec:
  selector:
    app: properties
  ports:
    - name: properties
      protocol: TCP
      port: 3000
      targetPort: 3000