apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels: 
        app: rooms
    spec:
      containers:
        - name: rooms
          image: us.gcr.io/amp-dev-376317/rooms
          env:
            - name: MONGO_URI
              value: mongodb://rooms-mongo-srv:27017/rooms
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwr 
---
apiVersion: v1
kind: Service
metadata:
  name: rooms-srv
spec:
  selector:
    app: rooms
  ports:
    - name: rooms
      protocol: TCP
      port: 3000
      targetPort: 3000